export const  GET_PRODUCT_WOMEN_REQUEST ="GET_PRODUCT_WOMEN_REQUEST"
export const  GET_PRODUCT_WOMEN_SUCCESS ="GET_PRODUCT_WOMEN_SUCCESS"
export const  GET_PRODUCT_WOMEN_FAILURE ="GET_PRODUCT_WOMEN_FAILURE"

export const  GET_PRODUCT_MEN_REQUEST ="GET_PRODUCT_MEN_REQUEST"
export const  GET_PRODUCT_MEN_SUCCESS ="GET_PRODUCT_MEN_SUCCESS"
export const  GET_PRODUCT_MEN_FAILURE ="GET_PRODUCT_MEN_FAILURE"
